### ISSUE TITLE
single-day opt-ins

### ISSUE THREAD

**Issue by courajs** [chrobid/pairing-bot#1]
It would be cool to be able to do the opposite of skip a day - opt in to pairing tomorrow without changing my schedule!

**Comment by chrobid** [comment]
I agree! Hopefully I'll get time to work on this this week.

**Comment by chrobid** [comment]
Duplicate of #2

**Comment by chrobid** [comment]
Duplicate of #2 

Sorry I'm still getting the hang of the issue tracker :)
